import {
  Badge,
  BadgeCheck,
  BatteryCharging,
  Bike,
  BookOpen,
  CalendarDays,
  CalendarRange,
  CircleGauge,
  ClipboardCheck,
  Disc,
  Dumbbell,
  FileCheck,
  Footprints,
  Gauge,
  Hand,
  LifeBuoy,
  MapPin,
  MapPinned,
  Moon,
  Package,
  Route,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Sun,
  TrafficCone,
  UsersRound,
  Warehouse,
  Wrench,
} from 'lucide-react';

export const contentIcons = {
  badge: Badge,
  'badge-check': BadgeCheck,
  'battery-charging': BatteryCharging,
  bike: Bike,
  'book-open': BookOpen,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'circle-gauge': CircleGauge,
  'clipboard-check': ClipboardCheck,
  disc: Disc,
  dumbbell: Dumbbell,
  fileCheck: FileCheck,
  'file-check': FileCheck,
  footprints: Footprints,
  gauge: Gauge,
  hand: Hand,
  'life-buoy': LifeBuoy,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  moon: Moon,
  package: Package,
  route: Route,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  sun: Sun,
  'traffic-cone': TrafficCone,
  'users-round': UsersRound,
  warehouse: Warehouse,
  wrench: Wrench,
};

export type ContentIconName = keyof typeof contentIcons;

export function getContentIcon(name: string) {
  return contentIcons[name as ContentIconName] ?? Wrench;
}
